### ISSUE TITLE
pillar syntax for filter with level and facility not x,y,z

### ISSUE THREAD

**Issue by kmkramer** [saltstack-formulas/syslog-ng-formula#10]
default SL 6x/7x syslog-ng config has this type of syntax. How do I mimic that in the pillar?

`filter f_default    { level(info..emerg) and
                        not (facility(mail)
                        or facility(authpriv)
                        or facility(cron)); };`

**Comment by n-rodriguez** [comment]
```
filter:
  - f_default:
    - =level(info..emerg) and not (facility(mail) or facility(authpriv) or facility(cron))
```

**Comment by n-rodriguez** [comment]
Here a complete example for Debian : [pillar.debian.example](https://github.com/saltstack-formulas/syslog-ng-formula/blob/master/pillar.debian.example). There is the same type of syntax, but you might need to adapt it for your distro.

**Comment by kmkramer** [comment]
yes thanks. the only other weird thing I'm seeing is spacing on certain items

`source s_sys {
  unix-dgram("/dev/log");
  file("/proc/kmsg"program_override("kernel"));
};
`
there should be a space before program. syslog-ng doesn't seem to care but visually not ideal

**Comment by n-rodriguez** [comment]
yes,  it's a known 'bug'. it's even worse when you have nested config like remote log :

```
destination d_remote_log {
  tcp("x.x.x.x"port(xxx)tls(ca_dir("/etc/syslog-ng/ssl/ca.d")key_file("/etc/syslog-ng/ssl/keys.d/client.key")cert_file("/etc/syslog-ng/ssl/certs.d/client.crt")));
};
```
but as you said syslog-ng doesn't care.

**Comment by kmkramer** [comment]
sorry one more thing I can't get going. specifying a port on a destination

pillar- d_elk:
`    - udp:
      - elk.example.com
      - port(5000)`
results in
`destination d_elk {
  udp("elk.example.com port(5000))");
};`

needs to be
`destination d_elk {
  udp("elk.example.com" port(5000));
};`

**Comment by n-rodriguez** [comment]
```
- d_elk:
  - udp:
     - elk.example.com 
     - port: 5000
```

**Comment by kmkramer** [comment]
sorry. thought I had tried that during my troubleshooting.

thanks

**Comment by n-rodriguez** [comment]
no problem, you're welcome!
