### ISSUE TITLE
facility with "and" and "not"

### ISSUE THREAD

**Issue by kmkramer** [saltstack-formulas/syslog-ng-formula#9]
default SL 6x/7x syslog-ng config has this type of syntax. How do I mimic that in the pillar?

`filter f_default    { level(info..emerg) and
                        not (facility(mail)
                        or facility(authpriv)
                        or facility(cron)); };`

**Comment by n-rodriguez** [comment]
https://github.com/saltstack-formulas/syslog-ng-formula/blob/master/pillar.debian.example
